version: '3'

services:
  lab:
    build: ./
    image: visualize_spotify
    container_name: visualize_spotify_lab
    volumes:
      - ./:/home/jovyan/
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_RUNTIME_DIR=/tmp/runtime
      - JUPYTER_ENABLE_LAB=1
    command: "jupyter-lab --no-browser --ip=\"*\" --allow-root --port=8888 --NotebookApp.notebook_dir=/home/jovyan --LabApp.token=\"\" --LabApp.password=\"\""